name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Ruby via Ruby Version Manager (RVM)
        run: |
          curl -sSL https://get.rvm.io | bash -s stable
          source ~/.rvm/scripts/rvm
          rvm install ruby
          rvm use ruby --default

      - name: Update RubyGems
        run: gem update --system

      - name: Install Bundler
        run: gem install bundler

      - name: Build and Deploy with Jekyll
        uses: helaili/jekyll-action@2.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
